---
- name: Testing-playbook
  hosts: managed
  tasks:
  - name: Update apt-get repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
  
  - name: execute command
    command: hostnamectl
    register: result
    
  - name: Display Command
    debug:
      var: result.stdout_lines
